In [2]:
import pandas as pd
df = pd.read_parquet("../data/cleaned/results.parquet")

In [3]:
df.info()

<class 'pandas.DataFrame'>
Index: 114761 entries, 0 to 114776
Data columns (total 18 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Position            114761 non-null  int64
 1   Nom                 114761 non-null  str
 2   Club                113457 non-null  str
 3   Sexe                114761 non-null  str
 4   Categorie           114761 non-null  str
 5   Position Catégorie  114761 non-null  int64
 6   Temps               114761 non-null  str
 7   NomCourse           114761 non-null  str
 8   Date                114761 non-null  datetime64[us]
 9   Distance            114761 non-null  float64
 10  source_file         114761 non-null  str
 11  racekey             114761 non-null  str
 12  categorie_cleaned   114761 non-null  str
 13  temps_clean         114761 non-null  timedelta64[us]
 14  temps_sec           114761 non-null  int32
 15  speed_kmh           114761 non-null  float64
 16  year                114761 non-null  int32
 17  Nom_clean           114761 non-null  str
dtypes: datetime64[us](1), float64(2), int32(2), int64(2), str(10), timedelta64[us](1)
memory usage: 33.2 MB

In [4]:
print(len(df['Nom'].unique()))
print(len(df['Nom_clean'].unique()))

25178
24264

In [5]:
runner_counts = df["Nom_clean"].value_counts()
runner_counts.describe()

count    24264.000000
mean         4.729682
std         13.095986
min          1.000000
25%          1.000000
50%          1.000000
75%          3.000000
max        246.000000
Name: count, dtype: float64

In [6]:
runner_counts.value_counts().sort_index()

count
1      14177
2       3373
3       1565
4        946
5        632
       ...
211        1
228        1
231        1
242        1
246        2
Name: count, Length: 160, dtype: int64

In [7]:
# Coureurs ayant plusieurs valeurs de sexe différentes
incoherent_sexe = (
    df.groupby("Nom_clean")["Sexe"]
    .nunique()
    .reset_index()
)

# filtrer ceux qui ont plus d'un sexe
incoherent_sexe = incoherent_sexe[incoherent_sexe["Sexe"] > 1]

# récupérer la liste des noms
liste_coureurs_incoherents = incoherent_sexe["Nom_clean"].tolist()

In [8]:
df[df["Nom_clean"].isin(liste_coureurs_incoherents)] \
    .sort_values(["Nom_clean", "Date"])

,Position,Nom,Club,Sexe,Categorie,Position Catégorie,Temps,NomCourse,Date,Distance,source_file,racekey,categorie_cleaned,temps_clean,temps_sec,speed_kmh,year,Nom_clean
100079,233,Andre Claude,,F,V2F,6,1:03:34,Nandrin,2012-03-03,11.30,2012-CONDRUSIEN-NANDRIN-11.30.pdf,nandrin_2012-03-03_11.3,A2,0 days 01:03:34,3814,10.665967,2012,ANDRE CLAUDE
93505,293,Andre Claude,,F,V2F,6,1:05:35,La Neupreenne,2012-03-18,12.00,2012-CONDRUSIEN-NEUPRE-11.98.pdf,la neupreenne_2012-03-18_12.0,A2,0 days 01:05:35,3935,10.978399,2012,ANDRE CLAUDE
49808,229,Andre Claude,,F,V2F,7,1:00:56,Terwagne,2012-04-20,10.90,2012-CONDRUSIEN-TERWAGNE-10.90.pdf,terwagne_2012-04-20_10.9,A2,0 days 01:00:56,3656,10.733042,2012,ANDRE CLAUDE
55556,242,Andre Claud,,F,V2F,8,1:22:48,Bois & Borsu,2012-05-05,14.70,2012-CONDRUSIEN-BOIS&BORSU-14.70.pdf,bois & borsu_2012-05-05_14.7,A2,0 days 01:22:48,4968,10.652174,2012,ANDRE CLAUDE
103093,233,Andre Claude,,F,V2F,5,1:12:22,A Pid Po L'Bwes - Fraiture,2012-05-11,12.30,2012-CONDRUSIEN-FRAITURE-12.30.pdf,a pid po l'bwes - fraiture_2012-05-11_12.3,A2,0 days 01:12:22,4342,10.198065,2012,ANDRE CLAUDE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85419,236,Xxx,,X,XXX,0,1:25:07,Jogging Du Congo - Ciney,2015-06-19,11.37,2015-CONDRUSIEN-CINEY-11.37.pdf,jogging du congo - ciney_2015-06-19_11.37,XXX,0 days 01:25:07,5107,8.014882,2015,XXX
67254,116,Xxx,,X,XXX,0,1:24:55,La Run'Essence - Hermalle-Sous-Huy,2019-06-02,14.50,190602-CONDRUSIEN-CHRONORACE-HERMALLE SOUS HUY...,la run'essence - hermalle-sous-huy_2019-06-02_...,XXX,0 days 01:24:55,5095,10.245339,2019,XXX
106077,164,Xxx,,X,XXX,0,01:04:39,La Neupreenne - Neupre,2021-10-10,9.42,211010-CONDRUSIEN-GOAL TIMING-NEUPRE-10000.pdf,la neupreenne - neupre_2021-10-10_9.42,XXX,0 days 01:04:39,3879,8.742459,2021,XXX
84234,101,Xxx,,X,XXX,0,01:33:09,Le Jogging Des Coccinelles - Chevetogne,2022-07-01,10.80,220701-CONDRUSIEN-GOALTIMING-LE JOGGING DES CO...,le jogging des coccinelles - chevetogne_2022-0...,XXX,0 days 01:33:09,5589,6.956522,2022,XXX
67989,66,Xxx,,X,XXX,0,04:01:13,Le Jogging De Villers-Le-Temple,2024-07-26,25.00,240726-CONDRUSIEN-GOALTIMING-LES JOGGING & TRA...,le jogging de villers-le-temple_2024-07-26_25.0,XXX,0 days 04:01:13,14473,6.218476,2024,XXX

In [6]:
df[df['Nom_clean'] == "CAO CHRISTOPHE"]

,Position,Nom,Club,Sexe,Categorie,Position Catégorie,Temps,NomCourse,Date,Distance,source_file,racekey,categorie_cleaned,temps_clean,temps_sec,speed_kmh,year,Nom_clean
4082,212,Cao Christophe,,X,XXX,0,1:01:46,La Corrida Des Fermes Et Chateaux - Villers-Le...,2017-07-28,11.200,170728-CONDRUSIEN-CHRONORACE-VILLERS LE TEMPLE...,la corrida des fermes et chateaux - villers-le...,XXX,0 days 01:01:46,3706,10.879655,2017,CAO CHRISTOPHE
6920,119,Cao Christophe,Chicken Run,H,V1H,27,0:57:50,Les Tidges D'Havlondje - Havelange,2013-10-12,11.700,2013-CONDRUSIEN-NEW-HAVELANGE-11.70.pdf,les tidges d'havlondje - havelange_2013-10-12_...,V1,0 days 00:57:50,3470,12.138329,2013,CAO CHRISTOPHE
8341,152,Cao Christophe,,H,V1H,59,0:58:15,Neupre,2011-04-10,11.200,2011 - CONDRUZIEN ET AVENIR - NEUPRE (11.2).pdf,neupre_2011-04-10_11.2,V1,0 days 00:58:15,3495,11.536481,2011,CAO CHRISTOPHE
9670,165,Cao Christophe,Chicken Run,H,V1H,41,0:58:49,Jogging Des 2 Provinces - Bois & Borsu,2013-05-04,11.500,2013-CONDRUSIEN-BOISETBORSU-11.50.pdf,jogging des 2 provinces - bois & borsu_2013-05...,V1,0 days 00:58:49,3529,11.731369,2013,CAO CHRISTOPHE
12777,165,Cao Christophe,,H,V1,60,1:19:23,Bois Et Borsu,2010-05-01,14.700,2010 - ARCHIVE - BOIS ET BORSU (14.7).pdf,bois et borsu_2010-05-01_14.7,V1,0 days 01:19:23,4763,11.110645,2010,CAO CHRISTOPHE
13422,156,Cao Christophe,Chicken Run,H,V1H,46,0:57:33,La Condrusienne - Solieres,2012-06-15,10.500,2012-CONDRUSIEN-SOLIERES-10.50.pdf,la condrusienne - solieres_2012-06-15_10.5,V1,0 days 00:57:33,3453,10.947003,2012,CAO CHRISTOPHE
14042,218,Cao Christophe,Chicken Run,H,V1H,79,1:08:13,Tihange,2012-03-25,12.700,2012-CONDRUSIEN-TIHANGE-12.70.pdf,tihange_2012-03-25_12.7,V1,0 days 01:08:13,4093,11.170291,2012,CAO CHRISTOPHE
15386,163,Cao Christophe,Chicken Run,H,VE1,37,0:58:15,Le Jogging Des 2 Provinces - Bois Et Borsu,2014-05-03,11.500,CONDRUSIEN-NEW-BOISETBORSU-11.5.pdf,le jogging des 2 provinces - bois et borsu_201...,V1,0 days 00:58:15,3495,11.845494,2014,CAO CHRISTOPHE
17247,155,Cao Christophe,Chicken Run,H,V1H,42,1:02:06,La Corrida Des Fermes Et Chateaux - Villers-Le...,2013-07-26,11.480,2013-CONDRUSIEN-VILLERSLETEMPLE-11.48.pdf,la corrida des fermes et chateaux - villers-le...,V1,0 days 01:02:06,3726,11.091787,2013,CAO CHRISTOPHE
18452,153,Cao Christophe,,H,V1,44,1:01:44,Jogging De Modave,2010-05-15,11.300,2010 - ARCHIVE - MODAVE (11.3).pdf,jogging de modave_2010-05-15_11.3,V1,0 days 01:01:44,3704,10.982721,2010,CAO CHRISTOPHE
23124,147,Cao Christophe,Chicken Run,H,V1H,46,1:53:18,Li Binameye Des D'Zys - Fraiture,2012-09-29,19.500,2012-CONDRUSIEN-FRAITUREII-19.50.pdf,li binameye des d'zys - fraiture_2012-09-29_19.5,V1,0 days 01:53:18,6798,10.326567,2012,CAO CHRISTOPHE
25504,216,Cao Christophe,Chicken Run,H,VE1,61,1:32:50,Entre Vyle Et Campagne - Vyle-Tharoul,2014-05-30,16.600,2014-CONDRUSIEN-NEW-VYLE-16.6.pdf,entre vyle et campagne - vyle-tharoul_2014-05-...,V1,0 days 01:32:50,5570,10.728905,2014,CAO CHRISTOPHE
31841,307,Cao Christophe,,H,V1H,95,1:08:03,Villers-Le-Temple,2011-07-29,12.000,2011 - CONDRUZIEN - VILLERS-LE-TEMPLE (11.47).pdf,villers-le-temple_2011-07-29_12.0,V1,0 days 01:08:03,4083,10.580456,2011,CAO CHRISTOPHE
34689,95,Cao Christophe,Chicken Run,H,V1H,34,0:54:32,Jogging Du Congo - Ciney,2012-06-24,10.900,2012-CONDRUSIEN-CINEY-10.85.pdf,jogging du congo - ciney_2012-06-24_10.9,V1,0 days 00:54:32,3272,11.992665,2012,CAO CHRISTOPHE
34961,201,Cao Christophe,,H,VE1,37,1:00:09,Jogging Des 2 Provinces - Bois & Borsu,2015-05-15,11.500,2015-CONDRUSIEN-BOIS ET BORSU-11.50.pdf,jogging des 2 provinces - bois & borsu_2015-05...,V1,0 days 01:00:09,3609,11.471322,2015,CAO CHRISTOPHE
36113,244,Cao Christophe,,H,V1H,76,1:11:49,Les Foulees De Tihange,2011-04-03,13.175,2011 - CONDRUZIEN ET AVENIR - TIHANGE (13.0).pdf,les foulees de tihange_2011-04-03_13.175,V1,0 days 01:11:49,4309,11.007194,2011,CAO CHRISTOPHE
37740,115,Cao Christophe,Chicken Run,H,V1H,35,1:47:10,Le Binameye - Fraiture En Condroz,2013-09-28,19.470,2013-CONDRUSIEN-NEW-FRAITURE-19.47.pdf,le binameye - fraiture en condroz_2013-09-28_1...,V1,0 days 01:47:10,6430,10.900778,2013,CAO CHRISTOPHE
40504,121,Cao Christhophe,,H,V1,49,01:05:18,Villers Le Temple,2008-07-25,12.500,2008 - ARCHIVE - VILLERS-LE-TEMPLE (12.50).pdf,villers le temple_2008-07-25_12.5,V1,0 days 01:05:18,3918,11.485452,2008,CAO CHRISTOPHE
42007,192,Cao Christophe,Chicken Run,H,VE1,52,0:58:50,Jogging Saint-Martin - Nandrin,2014-02-22,11.300,2014-CONDRUSIEN-NEW-NANDRIN-11.30.pdf,jogging saint-martin - nandrin_2014-02-22_11.3,V1,0 days 00:58:50,3530,11.524079,2014,CAO CHRISTOPHE
42638,151,Cao Christophe,Chicken Run,H,V1H,41,0:56:38,Pailhe,2012-09-08,10.160,2012-CONDRUZIEN-PAILHE-10.20.pdf,pailhe_2012-09-08_10.16,V1,0 days 00:56:38,3398,10.763979,2012,CAO CHRISTOPHE
43739,100,Cao Christophe,Chicken Run,H,V1H,30,1:06:28,Ocquier,2012-08-25,12.600,2012-CONDRUZIEN-OCQUIER-12.60.pdf,ocquier_2012-08-25_12.6,V1,0 days 01:06:28,3988,11.374122,2012,CAO CHRISTOPHE
44129,154,Cao Christophe,Chicken Run,H,VE1,39,0:58:12,Jogging Saint Martin - Nandrin,2016-02-27,11.270,160227-CONDRUSIEN-NANDRIN-11270.pdf,jogging saint martin - nandrin_2016-02-27_11.27,V1,0 days 00:58:12,3492,11.618557,2016,CAO CHRISTOPHE
46226,158,Cao Christophe,Chicken Run,H,V1H,47,0:59:20,Jogging Saint-Martin - Nandrin,2013-03-02,11.300,2013-CONDRUSIEN-NANDRIN-11.30.pdf,jogging saint-martin - nandrin_2013-03-02_11.3,V1,0 days 00:59:20,3560,11.426966,2013,CAO CHRISTOPHE
46949,153,Cao Christophe,Chicken Run,H,V1H,52,0:56:33,Le Jgging De La Saint-Nicolas - Marchin,2012-11-24,10.960,2012-CONDRUSIEN-MARCHIN-10.96.pdf,le jgging de la saint-nicolas - marchin_2012-1...,V1,0 days 00:56:33,3393,11.628647,2012,CAO CHRISTOPHE
49418,167,Cao Christophe,Chicken Run,H,VE1,36,1:03:34,A Pid Po L'Bwes - Fraiture,2014-05-09,12.000,2014-CONDRUSIEN-NEW-FRAITURE-12.0.pdf,a pid po l'bwes - fraiture_2014-05-09_12.0,V1,0 days 01:03:34,3814,11.326691,2014,CAO CHRISTOPHE
49718,139,Cao Christophe,Chicken Run,H,V1H,39,0:54:16,Terwagne,2012-04-20,10.900,2012-CONDRUSIEN-TERWAGNE-10.90.pdf,terwagne_2012-04-20_10.9,V1,0 days 00:54:16,3256,12.051597,2012,CAO CHRISTOPHE
50709,191,Cao Christophe,Chiken Run,H,VE1,36,1:04:06,La Corrida Des Fermes & Chateaux - Villers-Le-...,2016-07-29,11.200,160729-CONDRUSIEN-VILLERS LE TEMPLE-11200.pdf,la corrida des fermes & chateaux - villers-le-...,V1,0 days 01:04:06,3846,10.483619,2016,CAO CHRISTOPHE
55500,186,Cao Christophe,Chicken Run,H,V1H,47,1:15:40,Bois & Borsu,2012-05-05,14.700,2012-CONDRUSIEN-BOIS&BORSU-14.70.pdf,bois & borsu_2012-05-05_14.7,V1,0 days 01:15:40,4540,11.656388,2012,CAO CHRISTOPHE
60463,201,Cao Christophe,Chicken Run,H,V1H,66,1:02:43,Les Avins,2012-02-25,12.000,2012-CONDRUSIEN-LES AVINS-12.00.pdf,les avins_2012-02-25_12.0,V1,0 days 01:02:43,3763,11.480202,2012,CAO CHRISTOPHE
62083,105,Cao Christophe,Chicken Run,H,V1H,30,2:01:45,Jogging Saint Martin - Nandrin,2015-02-28,20.010,2015-CONDRUSIEN-SAINT-MARTIN-NANDRIN-20.01.pdf,jogging saint martin - nandrin_2015-02-28_20.01,V1,0 days 02:01:45,7305,9.861191,2015,CAO CHRISTOPHE
62472,170,Cao Christophe,Chicken Run,H,V1H,48,0:58:30,La Neupreenne - Neupre,2013-03-17,11.000,2013-CONDRUSIEN-NEUPRE-11.00.pdf,la neupreenne - neupre_2013-03-17_11.0,V1,0 days 00:58:30,3510,11.282051,2013,CAO CHRISTOPHE
63437,161,Cao Christophe,Chicken Run,H,VE1,48,2:00:29,Li Binameye - Fraiture,2014-09-27,19.950,2014-CONDRUSIEN-NEW2-FRAITURE-19.8.pdf,li binameye - fraiture_2014-09-27_19.95,V1,0 days 02:00:29,7229,9.934984,2014,CAO CHRISTOPHE
65317,131,Cao Christophe,NaN,H,V1H,46,1:52:23,Li Binameye Des D'Zys - Fraiture,2011-09-24,19.500,2011 - CONDRUZIEN - FRAITURE II (19.5).pdf,li binameye des d'zys - fraiture_2011-09-24_19.5,V1,0 days 01:52:23,6743,10.410796,2011,CAO CHRISTOPHE
65763,161,Cao Christophe,,H,VE1,46,1:08:23,Les Foulees De Tihange - Tihange,2015-03-29,12.700,2015-CONDRUSIEN-FOULEES-TIHANGE-12.7.pdf,les foulees de tihange - tihange_2015-03-29_12.7,V1,0 days 01:08:23,4103,11.143066,2015,CAO CHRISTOPHE
66289,157,Cao Christophe,Chicken Run,H,VE1,39,0:55:52,La Neupreenne - Neupre,2015-03-15,10.840,2015-CONDRUSIEN-NEUPREENNE-NEUPRE-10.84.pdf,la neupreenne - neupre_2015-03-15_10.84,V1,0 days 00:55:52,3352,11.642005,2015,CAO CHRISTOPHE
68288,183,Cao Christophe,Chicken Run,H,V1H,53,1:02:08,Villers-Le-Temple,2012-07-27,11.350,2012-CONDRUZIEN-VILLERS-LE-TEMPLE-11.35.pdf,villers-le-temple_2012-07-27_11.35,V1,0 days 01:02:08,3728,10.960300,2012,CAO CHRISTOPHE
70016,111,Cao Christophe,,H,V1H,30,0:55:33,Les 10 Kms De Pailhe,2011-09-10,10.000,2011 - CONDRUZIEN - PAILHE (10.0).pdf,les 10 kms de pailhe_2011-09-10_10.0,V1,0 days 00:55:33,3333,10.801080,2011,CAO CHRISTOPHE
74077,166,Cao Christophe,Chicken Run,H,VE1,50,1:06:53,Les Foulees De Tihange,2014-03-30,12.700,2014-CONDRUSIEN-NEW-TIHANGE-12.70.pdf,les foulees de tihange_2014-03-30_12.7,V1,0 days 01:06:53,4013,11.392973,2014,CAO CHRISTOPHE
74498,121,Cao Christophe,Chick And Run,H,V1H,37,1:03:00,Le Jogging Des Poudingues - Ombret,2013-10-06,12.500,2013-CONDRUSIEN-NEW-OMBRET-12.50.pdf,le jogging des poudingues - ombret_2013-10-06_...,V1,0 days 01:03:00,3780,11.904762,2013,CAO CHRISTOPHE
75422,168,Cao Christophe,,H,V1,54,1:03:26,Villers-Le-Temple,2010-07-30,11.500,2010 - ARCHIVE - VILLERS-LE-TEMPLE (11.5).pdf,villers-le-temple_2010-07-30_11.5,V1,0 days 01:03:26,3806,10.877562,2010,CAO CHRISTOPHE
78103,153,Cao Christophe,Chicken Run,H,V1H,48,1:07:35,Les Foulees De Tihange,2013-03-24,12.700,2013-CONDRUSIEN-TIHANGE-12.70.pdf,les foulees de tihange_2013-03-24_12.7,V1,0 days 01:07:35,4055,11.274969,2013,CAO CHRISTOPHE
83324,156,Cao Christophe,Chicken Run,H,V1H,46,0:57:33,La Condrusienne - Solieres,2012-06-15,11.500,2012-CONDRUSIEN-SOLIERES-11.50.pdf,la condrusienne - solieres_2012-06-15_11.5,V1,0 days 00:57:33,3453,11.989574,2012,CAO CHRISTOPHE
86152,143,Cao Christophe,Chicken Run,H,V2,24,01:01:12,La Corrida Des Fermes Et Chateaux - Villers-Le...,2022-07-29,10.400,220729-CONDRUSIEN-GOALTIMING-LA CORRIDA DES FE...,la corrida des fermes et chateaux - villers-le...,V2,0 days 01:01:12,3672,10.196078,2022,CAO CHRISTOPHE
88108,300,Cao Christophe,Chickend Run,H,VE1,67,1:12:23,Corrida Des Fermes Et Chateaux - Villers-Le-Te...,2015-07-31,11.600,2015-CONDRUSIEN-VILLERS LE TEMPLE-11.60.pdf,corrida des fermes et chateaux - villers-le-te...,V1,0 days 01:12:23,4343,9.615473,2015,CAO CHRISTOPHE
92076,143,Cao Christophe,,H,V1,42,01:04:47,Ronde Des Fermes Et Chateaux - Villers-Le-Temple,2009-07-31,12.500,2009 - ARCHIVE - VILLERS LE TEMPLE (12.5).pdf,ronde des fermes et chateaux - villers-le-temp...,V1,0 days 01:04:47,3887,11.577052,2009,CAO CHRISTOPHE
93904,197,Cao Christophe,Chicken Run,H,VE1,54,0:57:31,La Neupreenne - Neupre,2014-03-16,11.300,2014-CONDRUSIEN-NEW-NEUPRE-11.10.pdf,la neupreenne - neupre_2014-03-16_11.3,V1,0 days 00:57:31,3451,11.787888,2014,CAO CHRISTOPHE
95411,159,Cao Christophe,NaN,H,V1H,45,00:59:06,Les Tidges D'Havlondje - Havelange,2011-10-22,11.710,2011 - CONDRUZIEN - HAVELANGE (11.7).pdf,les tidges d'havlondje - havelange_2011-10-22_...,V1,0 days 00:59:06,3546,11.888325,2011,CAO CHRISTOPHE
99433,203,Cao Christophe,,H,V1,77,0:58:30,La Neupreenne - Neupre,2010-03-21,10.500,2010 - ARCHIVE - NEUPRE (10.5).pdf,la neupreenne - neupre_2010-03-21_10.5,V1,0 days 00:58:30,3510,10.769231,2010,CAO CHRISTOPHE
100010,163,Cao Christophe,Chick And Run,H,V1H,46,0:58:04,Nandrin,2012-03-03,11.300,2012-CONDRUSIEN-NANDRIN-11.30.pdf,nandrin_2012-03-03_11.3,V1,0 days 00:58:04,3484,11.676234,2012,CAO CHRISTOPHE
101323,102,Cao Christophe,,H,V1,30,00:58:21,Seraing,2008-10-11,10.200,2008 - ARCHIVE - SERAING (10.20).pdf,seraing_2008-10-11_10.2,V1,0 days 00:58:21,3501,10.488432,2008,CAO CHRISTOPHE
101650,124,Cao Christophe,Chicken Run,H,V1H,43,1:05:27,Jogging Des Poudinges - Ombret,2012-10-07,12.400,2012-CONDRUSIEN-OMBRET-12.40.pdf,jogging des poudinges - ombret_2012-10-07_12.4,V1,0 days 01:05:27,3927,11.367456,2012,CAO CHRISTOPHE
103012,151,Cao Christophe,Chicken Run,H,V1H,51,1:04:25,A Pid Po L'Bwes - Fraiture,2012-05-11,12.300,2012-CONDRUSIEN-FRAITURE-12.30.pdf,a pid po l'bwes - fraiture_2012-05-11_12.3,V1,0 days 01:04:25,3865,11.456662,2012,CAO CHRISTOPHE
106021,108,Cao Christophe,Chicken Run,H,V2,16,00:58:18,La Neupreenne - Neupre,2021-10-10,9.420,211010-CONDRUSIEN-GOAL TIMING-NEUPRE-10000.pdf,la neupreenne - neupre_2021-10-10_9.42,V2,0 days 00:58:18,3498,9.694683,2021,CAO CHRISTOPHE
107038,128,Cao Christophe,,H,V1,56,01:15:48,Bois Et Borsu,2009-04-04,15.200,2009 - ARCHIVE - BOIS ET BORSU (15.2).pdf,bois et borsu_2009-04-04_15.2,V1,0 days 01:15:48,4548,12.031662,2009,CAO CHRISTOPHE
112376,173,Cao Christophe,Chicken Run,H,V2,34,01:17:52,Le Jogging De Villers-Le-Temple,2024-07-26,11.160,240726-CONDRUSIEN-GOALTIMING-LES JOGGING & TRA...,le jogging de villers-le-temple_2024-07-26_11.16,V2,0 days 01:17:52,4672,8.599315,2024,CAO CHRISTOPHE
113405,174,Cao Christophe,Chicken Run,H,V1H,52,0:59:05,Jogging De Modave,2012-05-18,11.300,2012-CONDRUSIEN-MODAVE-11.30.pdf,jogging de modave_2012-05-18_5.0,V1,0 days 00:59:05,3545,11.475317,2012,CAO CHRISTOPHE